---
- hosts: goslow
  vars:
    gopath: "{{ lookup('env','GOPATH') }}"
  become: yes
  tasks:

   - apt: name=nginx-full state=present
   - apt: name=postgresql state=present
   - apt: name=python state=present
   - apt: name=python-psycopg2 state=present
   - user: name=goslow

   - file: path=/etc/goslow state=directory
   - file: path=/var/log/goslow state=directory owner=goslow

   - copy: src={{ gopath }}/release/goslow dest=/usr/local/bin/goslow mode=0555
   - copy: src=goslow.conf dest=/etc/init/goslow.conf
   - copy: src=goslow.service dest=/lib/systemd/system/goslow.service
   - copy: src=nginx.conf dest=/etc/nginx/nginx.conf
   - copy: src=~/tmp/site-salt dest=/etc/goslow/site-salt force=no

   - postgresql_db: name=goslow
     become_user: postgres
     vars:
         ansible_ssh_pipelining: true
   - postgresql_user: db=goslow name=goslow priv=ALL
     become_user: postgres
     vars:
         ansible_ssh_pipelining: true

   - service: name=nginx state=restarted
   - service: name=goslow state=restarted
